name: markdown-question-bank
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pytest
  - click
  - pandoc=3.6.2  
  - weasyprint
  - make
  - pip
  - pip:
      - jinja2-cli
      - pfylter==0.2.1
